from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as PlatypusImage, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from io import BytesIO
from PIL import Image as PILImage, ImageDraw
import requests
import os
from datetime import datetime

class ReportGenerator:
    def __init__(self):
        self.width, self.height = A4
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()

    def _create_custom_styles(self):
        self.styles.add(ParagraphStyle(
            name='ReportTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=colors.HexColor('#1e40af'),  # Blue-800
            alignment=1  # Center
        ))
        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=colors.HexColor('#374151'),  # Gray-700
            borderPadding=5,
            borderWidth=0,
            borderBottomWidth=1,
            borderColor=colors.HexColor('#e5e7eb')
        ))
        self.styles.add(ParagraphStyle(
            name='InfoText',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#4b5563'),
            leading=14
        ))

    def _draw_header(self, canvas, doc):
        canvas.saveState()
        canvas.setFillColor(colors.HexColor('#1e40af'))
        canvas.rect(0, self.height - 50, self.width, 50, fill=1, stroke=0)
        
        canvas.setFillColor(colors.white)
        canvas.setFont('Helvetica-Bold', 18)
        canvas.drawString(0.5 * inch, self.height - 35, "Swappers AI - Inspection Report")
        
        canvas.setFont('Helvetica', 10)
        canvas.drawRightString(self.width - 0.5 * inch, self.height - 35, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        canvas.restoreState()

    def _draw_footer(self, canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.gray)
        canvas.drawString(0.5 * inch, 0.5 * inch, "Generated by Swappers AI Automated Defect Detection System")
        canvas.drawRightString(self.width - 0.5 * inch, 0.5 * inch, f"Page {doc.page}")
        canvas.restoreState()

    def _annotate_image(self, image_path, detections):
        """
        Draws bounding boxes on a local image using PIL.
        Returns a PIL Image object.
        """
        try:
            # Handle local paths or URLs
            if image_path.startswith("http"):
                # If it's a localhost URL, try to map it to local file system if possible
                if "localhost" in image_path and "uploads" in image_path:
                    filename = image_path.split("/")[-1]
                    local_path = os.path.join("uploads", filename)
                    if os.path.exists(local_path):
                        img = PILImage.open(local_path)
                    else:
                        print(f"Local file not found: {local_path}")
                        # Fallback to requests
                        response = requests.get(image_path, stream=True)
                        img = PILImage.open(response.raw)
                else:
                    # Fetch from remote URL
                    response = requests.get(image_path, stream=True)
                    img = PILImage.open(response.raw)
            else:
                img = PILImage.open(image_path)

            img = img.convert("RGB")
            draw = ImageDraw.Draw(img)
            
            # Try to load a better font
            try:
                from PIL import ImageFont
                # Try to load Arial or generic sans-serif
                font = ImageFont.truetype("arial.ttf", 36)
            except IOError:
                # Fallback to default
                font = ImageFont.load_default()

            # Draw detections
            for det in detections:
                # Key fix: support 'bbox' (from backend) and 'box' (legacy/frontend)
                box = det.get("bbox") or det.get("box") or []
                label = det.get("class") or det.get("label") or "Defect"
                conf = det.get("confidence", 0)

                if box and len(box) == 4:
                    # Ensure coordinates are integers
                    box = [int(c) for c in box]
                    
                    # Draw box
                    draw.rectangle(box, outline="#ef4444", width=5)
                    
                    # Draw label background
                    text_text = f"{label.upper()} ({conf:.0%})"
                    
                    # Get text size
                    left, top, right, bottom = draw.textbbox((0, 0), text_text, font=font)
                    text_w = right - left
                    text_h = bottom - top
                    
                    # Draw background rectangle for text
                    draw.rectangle(
                        [box[0], box[1] - text_h - 10, box[0] + text_w + 20, box[1]],
                        fill="#ef4444"
                    )
                    
                    # Draw text
                    draw.text((box[0] + 10, box[1] - text_h - 5), text_text, fill="white", font=font)

            return img
        except Exception as e:
            print(f"Error processing image: {e}")
            import traceback
            traceback.print_exc()
            return None

    def _draw_page(self, canvas, doc):
        self._draw_header(canvas, doc)
        self._draw_footer(canvas, doc)

    def generate(self, scan_data):
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=1.25*inch,
            bottomMargin=1*inch
        )

        elements = []

        # 1. Report Title
        elements.append(Paragraph(f"Vehicle Inspection Report #{scan_data.get('id', 'N/A')[-6:].upper()}", self.styles['ReportTitle']))

        # 2. Key Information Table
        info_data = [
            ["Inspector", scan_data.get('user_email', 'Unknown')],
            ["Company ID", scan_data.get('company_id', 'N/A')],
            ["Scan Date", scan_data.get('date', 'N/A')],
            ["Status", scan_data.get('status', 'Pending')]
        ]
        
        t = Table(info_data, colWidths=[2*inch, 4*inch])
        t.setStyle(TableStyle([
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('TEXTCOLOR', (0,0), (0,-1), colors.HexColor('#4b5563')),
            ('GRID', (0,0), (-1,-1), 1, colors.HexColor('#e5e7eb')),
            ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#f9fafb')),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 20))

        # 3. Defect Summary
        elements.append(Paragraph("Defect Summary", self.styles['SectionHeader']))
        
        detections = scan_data.get('detections', [])
        defect_counts = {}
        for d in detections:
            label = d.get("class") or d.get("label") or "Defect"
            defect_counts[label] = defect_counts.get(label, 0) + 1
            
        summary_data = [["Defect Type", "Count"]]
        if not defect_counts:
            summary_data.append(["No defects detected", "0"])
        else:
            for label, count in defect_counts.items():
                summary_data.append([label, str(count)])
                
        t_summary = Table(summary_data, colWidths=[4*inch, 2*inch])
        t_summary.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#eff6ff')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#1e40af')),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 1, colors.HexColor('#e5e7eb')),
            ('ALIGN', (1,0), (1,-1), 'CENTER'),
            ('PADDING', (0,0), (-1,-1), 6),
        ]))
        elements.append(t_summary)
        elements.append(Spacer(1, 20))

        # 4. Annotated Image
        image_url = scan_data.get('image_url')
        if image_url:
            elements.append(Paragraph("Visual Evidence", self.styles['SectionHeader']))
            
            # Process image to draw bounding boxes
            annotated_pil = self._annotate_image(image_url, detections)
            
            if annotated_pil:
                # Save to temp buffer for ReportLab
                img_buffer = BytesIO()
                annotated_pil.save(img_buffer, format='JPEG')
                img_buffer.seek(0)
                
                # Scale image to fit page width
                img_width, img_height = annotated_pil.size
                aspect = img_height / float(img_width)
                
                display_width = 6 * inch
                display_height = display_width * aspect
                
                # If height is too tall, limit it
                if display_height > 5 * inch:
                    display_height = 5 * inch
                    display_width = display_height / aspect

                p_image = PlatypusImage(img_buffer, width=display_width, height=display_height)
                elements.append(p_image)
            else:
                elements.append(Paragraph("Image could not be loaded.", self.styles['InfoText']))

        # Build PDF
        doc.build(
            elements,
            onFirstPage=self._draw_page,
            onLaterPages=self._draw_page
        )
        
        buffer.seek(0)
        return buffer
